require 'framework/sequel_plugins/vcap_validations'
require 'framework/sequel_plugins/vcap_serialization'
require 'framework/sequel_plugins/vcap_normalization'
require 'framework/sequel_plugins/vcap_relations'
require 'framework/sequel_plugins/vcap_guid'
